import re

def normalize_port(port):
    p = str(port).strip()
    known = re.match(
        r'^(GigabitEthernet|FastEthernet|Serial|Ethernet|Loopback|Vlan|Port-channel|Tunnel|TenGigabit)',
        p, re.IGNORECASE
    )
    if known:
        return p
    port_map = {
        '0/0': 'GigabitEthernet0/0', '0/1': 'GigabitEthernet0/1',
        '0/2': 'GigabitEthernet0/2', '0/3': 'GigabitEthernet0/3',
        '1/0': 'GigabitEthernet1/0', '1/1': 'GigabitEthernet1/1',
        'g0/0': 'GigabitEthernet0/0', 'g0/1': 'GigabitEthernet0/1',
        'f0/0': 'FastEthernet0/0', 'f0/1': 'FastEthernet0/1',
        'inside': 'GigabitEthernet0/0', 'outside': 'GigabitEthernet0/1',
        'dmz': 'GigabitEthernet0/2',
    }
    return port_map.get(p.lower(), 'GigabitEthernet' + p)


def extract_device_configs(cli_text):
    configs = {}
    current_hostname = None
    current_lines = []
    marker_pattern = re.compile(r'^!\s+---\s+(.+?)\s+---')
    for line in cli_text.split('\n'):
        m = marker_pattern.match(line)
        if m:
            if current_hostname and current_lines:
                configs[current_hostname] = '\n'.join(current_lines).strip()
            current_hostname = m.group(1).strip()
            current_lines = []
        elif current_hostname:
            current_lines.append(line)
    if current_hostname and current_lines:
        configs[current_hostname] = '\n'.join(current_lines).strip()
    return configs


def generate_pt_builder_script(data, cli_text):
    if not data:
        return ''
    lines = [
        '// PTBuilder Script - Generated by Keystone Automation',
        '// Paste this into Packet Tracer: Extensions > Builder Code Editor\n',
        'function configureIosDevice(name, cmds) {',
        "    try {",
        "        var d;",
        "        try { d = ipc.network().getDevice(name); } catch(e) {}",
        "        if (!d) try { d = network.getDevice(name); } catch(e) {}",
        "        if (!d) try { var n = ipc.appWindow().getActiveFile().getMainNetwork(); d = n.getDevice(name); } catch(e) {}",
        '        if (!d) return;',
        "        try { d.setPower(true); } catch(e) {}",
        "        var cl = d.getCommandLine();",
        "        if (!cl) return;",
        "        var fn = null;",
        '        if (typeof cl.enterCommand === "function") fn = function(c){cl.enterCommand(c);};',
        '        else if (typeof cl.sendCommand === "function") fn = function(c){cl.sendCommand(c);};',
        '        else if (typeof cl.execute === "function") fn = function(c){cl.execute(c);};',
        "        if (!fn) return;",
        "        for (var i = 0; i < cmds.length; i++) {",
        "            fn(cmds[i]);",
        "        }",
        "    } catch(e) {}",
        "}\n",
    ]
    devices = []
    links = []
    if isinstance(data, dict) and 'devices' in data:
        devices = data['devices']
        links = data.get('links', data.get('connections', []))
    elif isinstance(data, list):
        devices = data
    else:
        devices = []

    step = 0

    step += 1
    lines.append(f'// ===== {step}. Spawning Devices =====')
    x = 100
    y = 100
    device_positions = {}
    model_map = {
        'router': '2911', 'switch': '2960-24TT', 'firewall': '5506-X',
        'asa': '5506-X', 'pc': 'PC-PT', 'server': 'Server-PT',
        'hub': 'Hub-PT', 'cloud': 'Cloud-PT',
    }
    for i, d in enumerate(devices):
        if not d:
            continue
        name = d.get('hostname') or d.get('name') or f'Device{i + 1}'
        dtype = (d.get('type') or 'router').lower()
        model = d.get('model') or model_map.get(dtype, '2911')
        dev_x = x
        dev_y = y
        pos = d.get('position', {})
        if isinstance(pos, dict):
            dev_x = pos.get('x', x)
            dev_y = pos.get('y', y)
        elif isinstance(pos, (list, tuple)) and len(pos) >= 2:
            dev_x = pos[0]
            dev_y = pos[1]
        device_positions[name] = {'x': dev_x, 'y': dev_y, 'type': dtype}
        lines.append(f'addDevice("{name}", "{model}", {dev_x}, {dev_y});')
        x += 250
        if x > 1500:
            x = 100
            y += 300

    has_modules = False
    for d in devices:
        if not d:
            continue
        if d.get('modules'):
            if not has_modules:
                step += 1
                lines.append(f'\n// ===== {step}. Adding Hardware Modules =====')
                has_modules = True
            name = d.get('hostname') or d.get('name') or ''
            for mod in d['modules']:
                if mod.get('slot') and mod.get('model'):
                    lines.append(f'addModule("{name}", "{mod["slot"]}", "{mod["model"]}");')

    if links:
        step += 1
        lines.append(f'\n// ===== {step}. Linking Interfaces =====')
        for link in links:
            src = link.get('source', '')
            tgt = link.get('target', '')
            link_type = link.get('link_type') or link.get('type') or 'straight'
            if src and tgt and ':' in src and ':' in tgt:
                src_dev, src_port = src.split(':', 1)
                tgt_dev, tgt_port = tgt.split(':', 1)
                src_port = normalize_port(src_port)
                tgt_port = normalize_port(tgt_port)
                lines.append(f'addLink("{src_dev}", "{src_port}", "{tgt_dev}", "{tgt_port}", "{link_type}");')

    if cli_text:
        device_configs = extract_device_configs(cli_text)
        config_lines = []
        for name, commands in device_configs.items():
            raw = commands.replace('\\', '\\\\').replace('"', '\\"')
            cmd_list = [c.strip() for c in raw.split('\n') if c.strip() and not c.strip().startswith('!')]
            all_cmds = ['no', ' ', 'enable', 'configure terminal'] + cmd_list + ['end', 'write memory']
            arr = '", "'.join(all_cmds)
            config_lines.append(f'configureIosDevice("{name}", ["{arr}"]);')
        if config_lines:
            step += 1
            lines.append(f'\n// ===== {step}. Configuring Cisco IOS Devices =====')
            lines.extend(config_lines)

    pc_config_lines = []
    pc_types = {'pc', 'server'}
    for d in devices:
        if not d:
            continue
        name = d.get('hostname') or d.get('name') or ''
        dtype = (d.get('type') or '').lower()
        name_lc = name.lower()
        is_pc = dtype in pc_types or name_lc.startswith('pc') or name_lc.startswith('host') or name_lc.startswith('srv') or name_lc.startswith('laptop')
        if not is_pc:
            continue
        dhcp = d.get('dhcp') is True
        ip = d.get('ip') or d.get('ip_address') or ''
        mask = d.get('mask') or d.get('subnet_mask') or ''
        gw = d.get('gateway') or d.get('default_gateway') or ''
        dns = d.get('dns') or d.get('dns_server') or ''
        if dhcp or ip:
            pc_config_lines.append(f'configurePcIp("{name}", {str(dhcp).lower()}, "{ip}", "{mask}", "{gw}", "{dns}");')
    if pc_config_lines:
        step += 1
        lines.append(f'\n// ===== {step}. Configuring PC IP Settings =====')
        lines.extend(pc_config_lines)

    return '\n'.join(lines)
