// PTBuilder Script - Generated by Keystone Automation
// Paste this into Packet Tracer: Extensions > Builder Code Editor

// ===== Add Devices =====
addDevice("Device1","2911",100,100);
addDevice("Device2","2911",350,100);
