#!/usr/bin/env python3
"""
Packet Tracer Scriptable Builder - Option C

Uses Packet Tracer's built-in PTBuilder scripting interface to create .pkt files.
This approach leverages Packet Tracer's own file saving mechanism, avoiding the 
need to reverse-engineer the binary .pkt format.

Workflow:
1. Generate PTBuilder JavaScript from topology
2. User opens PT and runs script in PTBuilder Code Editor
3. PT creates the topology and saves as .pkt

Advantages:
- Works with all PT versions (8.2.2+)
- Cisco-approved scripting interface
- No binary format reverse-engineering needed
- IOS config can be applied post-creation
"""

import argparse
import json
import sys
from pathlib import Path
from format_parser import parse_file

class PTScriptableBuilder:
    """Generate PTBuilder JavaScript for topology"""
    
    def __init__(self, topology):
        self.topology = topology
        self.x_offset = 100
        self.y_offset = 100
        self.device_positions = {}
        self.warnings = []
    
    def generate_ptbuilder_script(self):
        """Generate complete PTBuilder JavaScript"""
        lines = [
            "// PTBuilder Script - Generated by Keystone Automation",
            "// Paste this into Packet Tracer: Extensions > Builder Code Editor\n",
        ]
        
        # Add devices
        if 'devices' in self.topology:
            lines.append("// ===== Add Devices =====")
            for device in self.topology['devices']:
                js = self._generate_device(device)
                if js:
                    lines.append(js)
        
        # Add links
        if 'links' in self.topology or 'connections' in self.topology:
            lines.append("\n// ===== Add Links =====")
            connections = self.topology.get('connections', self.topology.get('links', []))
            for conn in connections:
                js = self._generate_link(conn)
                if js:
                    lines.append(js)
        
        return '\n'.join(lines)
    
    def generate_ios_config_script(self):
        """Generate script to apply IOS configurations"""
        from topology_composer import TopologyComposer
        
        composer = TopologyComposer(self.topology)
        commands = composer.generate()
        
        lines = [
            "// IOS Configuration Commands",
            "// Apply these individually to each device via CLI tab\n",
        ]
        
        current_device = None
        for cmd in commands.split('\n'):
            if cmd.startswith('!===='):
                current_device = cmd.split('[')[1].split(']')[0] if '[' in cmd else 'Device'
                lines.append(f"\n// === {current_device} ===")
            elif cmd.strip():
                lines.append(f"// {cmd}")
        
        return '\n'.join(lines)
    
    def _generate_device(self, device):
        """Generate PTBuilder code for device"""
        name = device.get('name', f'Device{len(self.device_positions) + 1}')
        device_type = device.get('type', 'Router').lower()
        
        model_map = {
            'router': '2911',
            'switch': '2960-24TT',
            'firewall': 'ASAv',
            'asa': 'ASAv',
            'pc': 'PC-PT',
            'server': 'Server-PT',
            'hub': 'Hub-PT',
            'cloud': 'Cloud-PT',
            'switch-3750': '3750-24PS',
            'switch-2960': '2960-24TT',
            'switch-2950': '2950-24',
        }
        
        model = model_map.get(device_type, '2911')
        
        # Position device in grid
        x = self.x_offset
        y = self.y_offset
        self.device_positions[name] = (x, y)
        self.x_offset += 250
        
        if self.x_offset > 1500:
            self.x_offset = 100
            self.y_offset += 300
        
        return f'addDevice("{name}","{model}",{x},{y});'
    
    def _generate_link(self, connection):
        """Generate PTBuilder code for link"""
        source = connection.get('source', '')
        target = connection.get('target', '')
        
        if not source or not target or ':' not in source or ':' not in target:
            return None
        
        src_device, src_port = source.split(':', 1)
        tgt_device, tgt_port = target.split(':', 1)
        
        src_port = self._normalize_port(src_port)
        tgt_port = self._normalize_port(tgt_port)
        
        return f'addLink("{src_device}","{src_port}","{tgt_device}","{tgt_port}","straight");'
    
    def _normalize_port(self, port):
        """Convert port notation to PT format"""
        port_map = {
            '0/0': 'GigabitEthernet0/1',
            '0/1': 'GigabitEthernet0/2',
            '0/2': 'GigabitEthernet0/3',
            '0/3': 'GigabitEthernet0/4',
            '1/0': 'GigabitEthernet1/1',
            '1/1': 'GigabitEthernet1/2',
            'g0/0': 'GigabitEthernet0/1',
            'g0/1': 'GigabitEthernet0/2',
            'f0/0': 'FastEthernet0/1',
            'f0/1': 'FastEthernet0/2',
            'inside': 'GigabitEthernet0/1',
            'outside': 'GigabitEthernet0/2',
            'dmz': 'GigabitEthernet0/3',
        }
        
        normalized = port.lower().strip()
        return port_map.get(normalized, f'GigabitEthernet{port}')


def main():
    parser = argparse.ArgumentParser(
        description='Generate PTBuilder scripts for Packet Tracer',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate PTBuilder script
  %(prog)s network.yaml --output topology.js
  
  # Generate with IOS config comments
  %(prog)s network.yaml --output topology.js --include-config
  
  # Use different input format
  %(prog)s network.json --format json
        """
    )
    
    parser.add_argument('topology_file', help='Topology definition file (YAML/JSON/XML)')
    parser.add_argument('--output', '-o', required=True, help='Output PTBuilder script file')
    parser.add_argument('--format', '-f', choices=['yaml', 'json', 'xml'], 
                       help='Input format (auto-detect if not specified)')
    parser.add_argument('--include-config', action='store_true',
                       help='Include IOS config comments in output')
    
    args = parser.parse_args()
    
    # Load topology
    try:
        topology = parse_file(args.topology_file)
    except Exception as e:
        print(f"Error loading topology: {e}", file=sys.stderr)
        return 1
    
    # Generate script
    builder = PTScriptableBuilder(topology)
    ptbuilder_script = builder.generate_ptbuilder_script()
    
    # Add IOS config if requested
    if args.include_config:
        ptbuilder_script += "\n\n" + builder.generate_ios_config_script()
    
    # Save output
    try:
        Path(args.output).write_text(ptbuilder_script)
        print(f"✓ Generated: {args.output}")
        print(f"✓ {len(topology.get('devices', []))} devices")
        print(f"✓ {len(topology.get('links', []))} links")
        print("\nNext steps:")
        print("1. Open Cisco Packet Tracer")
        print("2. Go to Extensions > Builder Code Editor")
        print("3. Copy and paste the contents of this file")
        print("4. Click Run")
        print("5. Save the .pkt file")
        return 0
    except Exception as e:
        print(f"Error writing output: {e}", file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
