import json
import argparse
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'tools'))
from format_parser import parse_file


def is_ipv6(s):
    return ':' in str(s)


def wildcard_from_mask(mask):
    parts = [int(p) for p in mask.split('.')]
    return '.'.join(str(255 - p) for p in parts)


def ip_and_mask_to_network(ip, mask):
    from ipaddress import IPv4Network, IPv4Address
    net = IPv4Network(f"{ip}/{mask}", strict=False)
    return str(net.network_address)


def gen_full_topology(data):
    name = data.get('name', 'Full Topology')
    devices = data.get('devices', [])
    output = []
    output.append("! ========================================")
    output.append(f"! Full Topology: {name}")
    output.append("! Generated by Keystone Automation")
    output.append("! ========================================")
    output.append("")
    for d in devices:
        if not d or not d.get('hostname'):
            continue
        lines = []
        lines.append(f"! --- {d['hostname']} ---")
        lines.append(f"hostname {d['hostname']}")
        if d.get('domain_name'):
            lines.append(f"ip domain-name {d['domain_name']}")
        if d.get('vlans'):
            lines.append("! VLANs")
            for vl in d['vlans']:
                if vl.get('id'):
                    lines.append(f"vlan {vl['id']}")
                    if vl.get('name'):
                        lines.append(f" name {vl['name']}")
            lines.append("exit")
            for vl in d['vlans']:
                if vl.get('id') and (vl.get('ip') or vl.get('ipv6')):
                    lines.append(f"interface vlan {vl['id']}")
                    if vl.get('ip'):
                        lines.append(f" ip address {vl['ip']} {vl['mask']}")
                    if vl.get('ipv6'):
                        lines.append(f" ipv6 address {vl['ipv6']}")
                    lines.append(" no shutdown")
                    lines.append(" exit")
        if d.get('interfaces'):
            for f in d['interfaces']:
                lines.append(f"interface {f['name']}")
                if f.get('description'):
                    lines.append(f" description {f['description']}")
                if f.get('mode'):
                    lines.append(f" switchport mode {f['mode']}")
                    if f.get('access_vlan'):
                        lines.append(f" switchport access vlan {f['access_vlan']}")
                    if f.get('trunk_allowed'):
                        lines.append(f" switchport trunk allowed vlan {f['trunk_allowed']}")
                if f.get('ip') and f.get('mask'):
                    lines.append(f" ip address {f['ip']} {f['mask']}")
                if f.get('ipv6'):
                    lines.append(f" ipv6 address {f['ipv6']}")
                if f.get('nameif'):
                    lines.append(f" nameif {f['nameif']}")
                if f.get('security_level') is not None:
                    lines.append(f" security-level {f['security_level']}")
                if f.get('hsrp'):
                    hg = f['hsrp'].get('group', 1)
                    if f['hsrp'].get('ip'):
                        lines.append(f" standby {hg} ip {f['hsrp']['ip']}")
                    if f['hsrp'].get('priority'):
                        lines.append(f" standby {hg} priority {f['hsrp']['priority']}")
                    if f['hsrp'].get('preempt'):
                        lines.append(f" standby {hg} preempt")
                if f.get('dhcp'):
                    lines.append(" ip address dhcp")
                lines.append(" no shutdown")
                lines.append(" exit")
        if d.get('ospf'):
            pid = d['ospf'].get('process_id', 1)
            lines.append(f"router ospf {pid}")
            if d['ospf'].get('router_id'):
                lines.append(f" router-id {d['ospf']['router_id']}")
            if d.get('interfaces'):
                for f in d['interfaces']:
                    if f.get('ip') and f.get('mask'):
                        net = ip_and_mask_to_network(f['ip'], f['mask'])
                        wc = wildcard_from_mask(f['mask'])
                        lines.append(f" network {net} {wc} area {d['ospf'].get('area', 0)}")
            lines.append(" exit")
        if d.get('eigrp'):
            as_num = d['eigrp'].get('as', 100)
            lines.append(f"router eigrp {as_num}")
            if d.get('interfaces'):
                for f in d['interfaces']:
                    if f.get('ip') and f.get('mask'):
                        net = ip_and_mask_to_network(f['ip'], f['mask'])
                        wc = wildcard_from_mask(f['mask'])
                        lines.append(f" network {net} {wc}")
            lines.append(" no auto-summary")
            lines.append(" exit")
        if d.get('bgp'):
            bgp_as = d['bgp'].get('as', 65000)
            lines.append(f"router bgp {bgp_as}")
            if d['bgp'].get('router_id'):
                lines.append(f" bgp router-id {d['bgp']['router_id']}")
            if d['bgp'].get('networks'):
                for bn in d['bgp']['networks']:
                    mask_str = f" mask {bn['mask']}" if bn.get('mask') else ""
                    lines.append(f" network {bn['network']}{mask_str}")
            if d['bgp'].get('neighbors'):
                for nbr in d['bgp']['neighbors']:
                    ras = nbr.get('remote_as', bgp_as)
                    lines.append(f" neighbor {nbr['ip']} remote-as {ras}")
                    if nbr.get('update_source'):
                        lines.append(f" neighbor {nbr['ip']} update-source {nbr['update_source']}")
                    if nbr.get('next_hop_self'):
                        lines.append(f" neighbor {nbr['ip']} next-hop-self")
                    if nbr.get('ebgp_multihop'):
                        lines.append(f" neighbor {nbr['ip']} ebgp-multihop {nbr['ebgp_multihop']}")
            lines.append(" exit")
        if d.get('routes'):
            for r in d['routes']:
                tgt = r.get('next_hop', '')
                if is_ipv6(r['network']):
                    lines.append(f"ipv6 route {r['network']}/{r['mask']} {tgt}")
                else:
                    lines.append(f"ip route {r['network']} {r['mask']} {tgt}")
        if d.get('dhcp'):
            for p in d['dhcp'].get('pools', []):
                lines.append(f"ip dhcp pool {p['name']}")
                lines.append(f" network {p['network']} {p['mask']}")
                lines.append(f" default-router {p['gateway']}")
                if p.get('dns'):
                    lines.append(f" dns-server {p['dns']}")
                lines.append(" exit")
            for p in d['dhcp'].get('ipv6_pools', []):
                lines.append(f"ipv6 dhcp pool {p['name']}")
                lines.append(f" prefix-delegation pool {p['prefix']}")
                if p.get('dns'):
                    lines.append(f" dns-server {p['dns']}")
                lines.append(" exit")
        if d.get('nat'):
            for n in d['nat']:
                if n.get('type') == 'dynamic':
                    lines.append(f"ip nat inside source list {n.get('acl_id', '1')} interface {n['outside_interface']} overload")
        if d.get('ssh'):
            lines.append(f"crypto key generate rsa modulus {d['ssh'].get('key_size', 2048)}")
            lines.append("ip ssh version 2")
            lines.append(f"username {d['ssh'].get('username', 'admin')} secret {d['ssh'].get('password', 'cisco')}")
            if d['ssh'].get('ipv6_vty'):
                lines.append("ipv6 access-list VTY_ACL")
                lines.append(f" permit tcp {d['ssh'].get('vty_acl_ipv6', '2001:db8::/32')} any eq 22")
                lines.append(" exit")
            lines.append("line vty 0 15")
            lines.append(" login local")
            lines.append(" transport input ssh")
            if d['ssh'].get('ipv6_vty'):
                lines.append(" ipv6 access-class VTY_ACL in")
            lines.append(" exit")
        output.append("\n".join(lines))
    output.append("")
    output.append("! ========================================")
    output.append("! Topology Summary")
    output.append(f"! Devices: {sum(1 for d in devices if d and d.get('hostname'))}")
    output.append("! ========================================")
    return "\n\n".join(output)


def main():
    parser = argparse.ArgumentParser(description="Generate multi-device full topology configurations.")
    parser.add_argument("--file", help="Path to topology file (YAML, JSON, or XML)")
    parser.add_argument("--output", help="Path to save generated CLI config")
    args = parser.parse_args()
    if args.file:
        try:
            data = parse_file(args.file)
            config = gen_full_topology(data)
            print(config)
            if args.output:
                with open(args.output, 'w') as f:
                    f.write(config)
                print(f"\nSaved to {args.output}")
        except Exception as e:
            print(f"Error: {e}")
    else:
        print("Usage: python3 full_topology.py --file [topology.yaml]")


if __name__ == "__main__":
    main()
