import json
import argparse
import sys
import os
import re
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'tools'))
from format_parser import parse_file, normalize_entries, entry_name, normalize_interface_name, normalize_items


def is_ipv6(s):
    return ':' in str(s)


def wildcard_from_mask(mask):
    parts = [int(p) for p in mask.split('.')]
    return '.'.join(str(255 - p) for p in parts)


def ip_and_mask_to_network(ip, mask):
    from ipaddress import IPv4Network, IPv4Address
    net = IPv4Network(f"{ip}/{mask}", strict=False)
    return str(net.network_address)


def gen_full_topology(data):
    if isinstance(data, list):
        data = {'devices': data}
    elif not isinstance(data, dict):
        data = {}
    name = data.get('name', 'Full Topology')
    devices = [d for d in normalize_entries(data, preferred_keys=('devices',)) if isinstance(d, dict)]
    output = []
    output.append("! ========================================")
    output.append(f"! Full Topology: {name}")
    output.append("! Generated by Keystone Automation")
    output.append("! ========================================")
    output.append("")
    for d in devices:
        hostname = d.get('hostname') or d.get('_hostname') or d.get('name')
        if not hostname:
            continue
        lines = []
        lines.append(f"! --- {hostname} ---")
        lines.append(f"hostname {hostname}")
        if d.get('domain_name'):
            lines.append(f"ip domain-name {d['domain_name']}")
        if d.get('vlans'):
            lines.append("! VLANs")
            for vl in normalize_items(d['vlans']):
                if not isinstance(vl, dict):
                    continue
                if vl.get('id'):
                    lines.append(f"vlan {vl['id']}")
                    if vl.get('name'):
                        lines.append(f" name {vl['name']}")
            lines.append("exit")
            for vl in d['vlans']:
                if vl.get('id') and (vl.get('ip') or vl.get('ipv6')):
                    lines.append(f"interface vlan {vl['id']}")
                    if vl.get('ip'):
                        lines.append(f" ip address {vl['ip']} {vl['mask']}")
                    if vl.get('ipv6'):
                        lines.append(f" ipv6 address {vl['ipv6']}")
                    lines.append(" no shutdown")
                    lines.append(" exit")
        if d.get('interfaces'):
            for f in normalize_items(d['interfaces']):
                if not isinstance(f, dict):
                    continue
                lines.append(f"interface {normalize_interface_name(f.get('name'))}")
                if f.get('description'):
                    lines.append(f" description {f['description']}")
                if f.get('mode'):
                    lines.append(f" switchport mode {f['mode']}")
                    if f.get('access_vlan'):
                        lines.append(f" switchport access vlan {f['access_vlan']}")
                    if f.get('trunk_allowed'):
                        lines.append(f" switchport trunk allowed vlan {f['trunk_allowed']}")
                if f.get('ip') and f.get('mask'):
                    lines.append(f" ip address {f['ip']} {f['mask']}")
                if f.get('ipv6'):
                    lines.append(f" ipv6 address {f['ipv6']}")
                if f.get('nameif'):
                    lines.append(f" nameif {f['nameif']}")
                if f.get('security_level') is not None:
                    lines.append(f" security-level {f['security_level']}")
                if f.get('hsrp'):
                    hg = f['hsrp'].get('group', 1)
                    if f['hsrp'].get('ip'):
                        lines.append(f" standby {hg} ip {f['hsrp']['ip']}")
                    if f['hsrp'].get('priority'):
                        lines.append(f" standby {hg} priority {f['hsrp']['priority']}")
                    if f['hsrp'].get('preempt'):
                        lines.append(f" standby {hg} preempt")
                if f.get('dhcp'):
                    lines.append(" ip address dhcp")
                lines.append(" no shutdown")
                lines.append(" exit")
        if d.get('ospf'):
            pid = d['ospf'].get('process_id', 1)
            lines.append(f"router ospf {pid}")
            if d['ospf'].get('router_id'):
                lines.append(f" router-id {d['ospf']['router_id']}")
            if d.get('interfaces'):
                for f in normalize_items(d['interfaces']):
                    if not isinstance(f, dict):
                        continue
                    if f.get('ip') and f.get('mask'):
                        net = ip_and_mask_to_network(f['ip'], f['mask'])
                        wc = wildcard_from_mask(f['mask'])
                        lines.append(f" network {net} {wc} area {d['ospf'].get('area', 0)}")
            lines.append(" exit")
        if d.get('eigrp'):
            as_num = d['eigrp'].get('as', 100)
            lines.append(f"router eigrp {as_num}")
            if d.get('interfaces'):
                for f in normalize_items(d['interfaces']):
                    if not isinstance(f, dict):
                        continue
                    if f.get('ip') and f.get('mask'):
                        net = ip_and_mask_to_network(f['ip'], f['mask'])
                        wc = wildcard_from_mask(f['mask'])
                        lines.append(f" network {net} {wc}")
            lines.append(" no auto-summary")
            lines.append(" exit")
        if d.get('bgp'):
            bgp_as = d['bgp'].get('as', 65000)
            lines.append(f"router bgp {bgp_as}")
            if d['bgp'].get('router_id'):
                lines.append(f" bgp router-id {d['bgp']['router_id']}")
            if d['bgp'].get('networks'):
                for bn in d['bgp']['networks']:
                    mask_str = f" mask {bn['mask']}" if bn.get('mask') else ""
                    lines.append(f" network {bn['network']}{mask_str}")
            if d['bgp'].get('neighbors'):
                for nbr in d['bgp']['neighbors']:
                    ras = nbr.get('remote_as', bgp_as)
                    lines.append(f" neighbor {nbr['ip']} remote-as {ras}")
                    if nbr.get('update_source'):
                        lines.append(f" neighbor {nbr['ip']} update-source {normalize_interface_name(nbr['update_source'])}")
                    if nbr.get('next_hop_self'):
                        lines.append(f" neighbor {nbr['ip']} next-hop-self")
                    if nbr.get('ebgp_multihop'):
                        lines.append(f" neighbor {nbr['ip']} ebgp-multihop {nbr['ebgp_multihop']}")
            lines.append(" exit")
        if d.get('routes'):
            for r in d['routes']:
                tgt = r.get('next_hop', '')
                net = str(r.get('network', '')).strip()
                mask = r.get('mask', None)
                # IPv6 route handling: network may already include prefix length (e.g. ::/0)
                if net and (':' in net):
                    if '/' in net:
                        prefix = net
                    elif mask is not None:
                        # mask for IPv6 may be numeric (0-128)
                        prefix = f"{net}/{mask}"
                    else:
                        prefix = net
                    lines.append(f"ipv6 route {prefix} {tgt}")
                else:
                    # IPv4 route
                    lines.append(f"ip route {net} {mask if mask is not None else ''} {tgt}")
        if d.get('dhcp'):
            for p in normalize_items(d['dhcp'].get('pools', [])):
                if not isinstance(p, dict):
                    continue
                lines.append(f"ip dhcp pool {p['name']}")
                lines.append(f" network {p['network']} {p['mask']}")
                lines.append(f" default-router {p['gateway']}")
                if p.get('dns'):
                    lines.append(f" dns-server {p['dns']}")
                lines.append(" exit")
            for p in normalize_items(d['dhcp'].get('ipv6_pools', [])):
                if not isinstance(p, dict):
                    continue
                lines.append(f"ipv6 dhcp pool {p['name']}")
                lines.append(f" prefix-delegation pool {p['prefix']}")
                if p.get('dns'):
                    lines.append(f" dns-server {p['dns']}")
                lines.append(" exit")
        if d.get('type') in ('pc', 'server', 'laptop'):
            grp = str(d.get('group') or d.get('hostname') or '')
            m = re.search(r'(\d+)', grp)
            subnet = min(3, max(1, ((int(m.group(1)) - 1) // 4) + 1)) if m else 1
            pos = d.get('pos', 0)
            suffix = 100 if d.get('type') == 'server' else 11 if str(pos) == '0' or str(hostname).startswith('PC1_') else 12 if str(pos) == '1' or str(hostname).startswith('PC2_') else 100
            ip = d.get('ip') or f"192.168.{subnet}.{suffix}"
            mask = d.get('mask', '255.255.255.0')
            gateway = d.get('gateway') or f"192.168.{subnet}.1"
            dns = d.get('dns') or f"192.168.{subnet}.100"
            lines.append(f'configurePcIp("{hostname}", false, "{ip}", "{mask}", "{gateway}", "{dns}");')
            ipv6 = d.get('ipv6') or d.get('ipv6_address') or f"2001:db8:{subnet}::{suffix}/64"
            ipv6_gw = d.get('ipv6_gateway') or f"2001:db8:{subnet}::1"
            ipv6_dns = d.get('ipv6_dns') or f"2001:db8:{subnet}::100"
            lines.append(f'// IPv6: {ipv6} | gw {ipv6_gw} | dns {ipv6_dns}')
        if d.get('nat'):
            for n in normalize_items(d['nat']):
                if not isinstance(n, dict):
                    continue
                if n.get('type') == 'dynamic':
                    lines.append(f"ip nat inside source list {n.get('acl_id', '1')} interface {normalize_interface_name(n['outside_interface'])} overload")
        if d.get('ssh'):
            lines.append(f"crypto key generate rsa modulus {d['ssh'].get('key_size', 2048)}")
            lines.append("ip ssh version 2")
            lines.append(f"username {d['ssh'].get('username', 'admin')} secret {d['ssh'].get('password', 'cisco')}")
            if d['ssh'].get('ipv6_vty'):
                lines.append("ipv6 access-list VTY_ACL")
                lines.append(f" permit tcp {d['ssh'].get('vty_acl_ipv6', '2001:db8::/32')} any eq 22")
                lines.append(" exit")
            lines.append("line vty 0 15")
            lines.append(" login local")
            lines.append(" transport input ssh")
            if d['ssh'].get('ipv6_vty'):
                lines.append(" ipv6 access-class VTY_ACL in")
            lines.append(" exit")
        output.append("\n".join(lines))
    output.append("")
    output.append("! ========================================")
    output.append("! Topology Summary")
    output.append(f"! Devices: {sum(1 for d in devices if d.get('hostname') or d.get('_hostname') or d.get('name'))}")
    output.append("! ========================================")
    return "\n\n".join(output)


def main():
    parser = argparse.ArgumentParser(description="Generate multi-device full topology configurations.")
    parser.add_argument("--file", help="Path to topology file (YAML, JSON, or XML)")
    parser.add_argument("--output", help="Path to save generated CLI config")
    args = parser.parse_args()
    if args.file:
        try:
            data = parse_file(args.file)
            config = gen_full_topology(data)
            print(config)
            if args.output:
                with open(args.output, 'w') as f:
                    f.write(config)
                print(f"\nSaved to {args.output}")
        except Exception as e:
            print(f"Error: {e}")
    else:
        print("Usage: python3 full_topology.py --file [topology.yaml]")


if __name__ == "__main__":
    main()
